name              'resolver'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Configures /etc/resolv.conf via attributes'
version           '4.0.2'
source_url        'https://github.com/sous-chefs/resolver'
issues_url        'https://github.com/sous-chefs/resolver/issues'
chef_version      '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'mac_os_x'
supports 'openbsd'
supports 'opensuse'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'solaris2'
supports 'suse'
supports 'ubuntu'
