name              'resolver'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Configures /etc/resolv.conf via attributes'
version           '2.1.0'
source_url        'https://github.com/sous-chefs/resolver'
issues_url        'https://github.com/sous-chefs/resolver/issues'
chef_version      '>= 12.15'

supports          'ubuntu'
supports          'debian'
supports          'fedora'
supports          'centos'
supports          'redhat'
supports          'oracle'
supports          'scientific'
supports          'amazon'
supports          'freebsd'
supports          'openbsd'
supports          'mac_os_x'
supports          'solaris2'
supports          'opensuse'
supports          'opensuseleap'
supports          'suse'
